### ISSUE TITLE
Mixed Content issues when serving a nectar instance over https

### ISSUE THREAD

**Issue by dolled-possum** [hyperware-ai/client-encryptor#4]
(Hope this is the right place to log this.)  I was attempting to run a pair of nectar instance for a chess game on a remote ubuntu server.  If I used http to connect to the instances, I had no issues playing a nice game of chess between the two instances.  But if I connected via https (thru a proxy), everything went fine as far as the login and even registration if I started from scratch, but I couldn't successfully launch the chess app due to the use of an insecure websocket connection: 
`index.js:71 Mixed Content: The page at 'https://two-nectar.plymouth.network/chess:chess:uqbar/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://two-nectar.plymouth.network/chess:chess:uqbar/'. This request has been blocked; this endpoint must be available over WSS.`
I hope I'm right in deducing that the issue is here in the index.ts constructor, but if not, hopefully we can attach the issue where appropriate.  Would it be possible to detect what protocol is being used and match the security level?

**Comment by willbach** [comment]
yes this is the right place. I will update this repo and put in an update to the `chess` app. Thanks!

**Comment by willbach** [comment]
This has been fixed and will be available in the main `kinode` repo (new name) as part of this PR: https://github.com/uqbar-dao/kinode/pull/167

**Comment by dolled-possum** [comment]
> This has been fixed and will be available in the main `kinode` repo (new name) as part of this PR: [uqbar-dao/kinode#167](https://github.com/uqbar-dao/kinode/pull/167)

Tremendous, thanks!  When merged, that'll make for more compelling demonstrations of the deployed nodes behind an https reverse proxy :-)
